### ISSUE TITLE
Properties set after initialization are ignored

### ISSUE THREAD

**Issue by attheodo** [uacaps/PageMenu#12]
Hey @fahlout,

thanks for the new release. I changed the initialisation method of PageMenu to include frame: and options: parameters. I set options to nil. I kept the rest of my code that was setting various properties after instantiation but PageMenu seems to be ignoring them. It also appears to ignore the default values you've set? This is the output https://www.dropbox.com/s/clfrtjv9t4nit11/Screen%20Shot%202015-02-03%20at%2011.32.09%20AM.png?dl=0

**Comment by attheodo** [comment]
Also the hideTopMenuBar property appears to have no effect even when passed in the options dictionary

https://gist.github.com/attheodo/f8bcecaf3f361635b493

**Comment by fahlout** [comment]
All option parameters should be placed in a dictionary before initialization and passed in when initializing PageMenu. Anything set after initialization is not guaranteed to work. Is there a specific need that you have to set them after initialization? Maybe I was just not thinking of something there. On your first screenshot it seems to use the default settings which are usually not very useful and are just supposed to give you a starting point until you know what you want to customize, which you already know that. In your code on the second screenshot it seems that you're not setting the parameters to nil and it looks like the right setup which should work. the hideTopMenuBar currently only works if you don't set menuHeight to anything, but i agree that that is not a good way of doing it so I'll make sure to fix that. 

Thanks!

**Comment by fahlout** [comment]
hideTopMenuBar should work as expected now. I pushed a new commit for that

**Comment by attheodo** [comment]
Thanks @fahlout. In my project, I can bear with having to set properties prior to initialising. In some other cases, the developer might want to customise further according to runtime situations. For example update a label on the menu or change it's color. In my opinion the component would be more versatile if you could set properties after initialisation.

One final thing. I noticed that If I try to use PageMenu through Cocoapods, I will always get `undeclared type CAPSMenu`. Is is something I am doing wrong? I've tried `import PageMenu` without success. What am I missing? Thanks

**Comment by fahlout** [comment]
It's working for you right now though? I will look into being able to set properties after initialization.

Honestly, I have had the same issue with cocoa pods. Swift support is currently in beta for cocoa pods and there is not much documentation on how to make a swift library work with it. I followed how other projects did it on github but it seems to not work correctly. I would recommend just adding the page menu file to your project instead of using cocoa pods right now even though theoretically either one should work. Sorry for the inconvenience.

**Comment by attheodo** [comment]
Yeah, it works wonderful for me. I've setup my view the way I wanted and I can tell your effort with PageMenu saved me tons of time. I can't thank you more.

The thing with CocoaPods probably has something to do with naming conventions. I'll try to investigate when I have time and if I find a solution I'll kindly submit a pull request.

**Comment by fahlout** [comment]
I'm glad it works for you!

I would definitely appreciate your help solving the CocoaPods problem. Thanks!

**Comment by chlebta** [comment]
@attheodo  @fahlout  did you solved this issue updating properties after init , I got same issue I need to customise `pageMenu bar` depending on which tab is selected.
