### ISSUE TITLE
How would I change viewcontrollers with a timer to create a slideshow.

### ISSUE THREAD

**Issue by londonbridges13** [uacaps/PageMenu#132]
I saw a taptimer in the CAPSPageMenu.swift file, could I use that and if so how? 
If any other way please let me know.

**Comment by frisovanderwerf** [comment]
Hi,
I'm not so familiar with PageMenu yet, so I don't know if that's possible. But maybe this is something you're searching for: https://github.com/zvonicek/ImageSlideshow
Good luck!

**Comment by londonbridges13** [comment]
Thanks I figured it out
