### ISSUE TITLE
NavigationBar and ScrollMenu translucency

### ISSUE THREAD

**Issue by IVANKRUPSKI** [uacaps/PageMenu#149]
Hi everyone,

Does anyone know how to make NavigationBar and ScrollMenu translucent similar to how standard NavBar/TabBar translucent are.
Many thanks in advance.

**Comment by curiousurick** [comment]
You would have to extend the page menu under the navigation bar and move the inset of the scrollMenu below the navigation bar as well as the actually scrollViews. This way, it will let them scroll under the navigation bar.
