### ISSUE TITLE
Set PageMenu title color

### ISSUE THREAD

**Issue by jefferyleo** [uacaps/PageMenu#153]
How do I set the title font color in page menu?
sampleText.title = "testing" (how to set color for this title?)

**Comment by MatthewYork** [comment]
Currently, there is now way to set the selected and unselected color or font for a particular controller. There are currently two options extended in the CAPSPageMenuConfiguration class for setting the selected and unselected colors.

```Swift
open var selectedMenuItemLabelColor : UIColor = UIColor.white
open var unselectedMenuItemLabelColor : UIColor = UIColor.lightGray
```

New features will soon be added to help with your problem, but I am going to close this for now as it will be part of a larger enhancement.
