### ISSUE TITLE
xib

### ISSUE THREAD

**Issue by chenenyu** [uacaps/PageMenu#20]
xib's default size is 600*600, the UI on Simulator won't be scaled by inferred, besides your demos... I'm weak in English, and hope u can understand my description...

**Comment by fahlout** [comment]
Not sure exactly what you mean, but if you set up PageMenu as shown in the demos and in the Readme with the correct frame you should have no problems with resizing. If it is something within the view not resizing then it's not a problem with PageMenu, but rather with constraints on your UI elements not being set

**Comment by chenenyu** [comment]
I have debuged your demos: println("\(self.view.frame.width),\(self.view.frame.height)"). The result is:600,600. But if i design the UI by code, and set nil xib, just like: var controller1 : TestViewController = TestViewController(nibName: nil, bundle: nil), the size is OK~    God, ios is new to me...

**Comment by fahlout** [comment]
It should all resize just fine if set up the same way as it is in the demos. Without seeing your set up I don't know what could cause the issue

**Comment by MatthewYork** [comment]
Please ensure that this calc is done after the initial load (recommended in viewDidAppear:). This issue should be resolved as of 2.0.0
