### ISSUE TITLE
change default page

### ISSUE THREAD

**Issue by bassel271** [uacaps/PageMenu#21]
is it possible to change the default page??

**Comment by fahlout** [comment]
Right now the only way of starting out with a page index other than 0 is to call the moveToPage function, but you are right, setting the index in the customization options would be nice and I'll work that in when I get the chance

**Comment by fahlout** [comment]
Please check out the changes in the develop branch and let me know if you find any errors with setting startingPageIndex, which will set the default page

**Comment by bassel271** [comment]
It's working with no errors. 
Yesterday I tried to modify the code my self, I changed currentPageIndex and lastPageIndex values but it didn't work, now I know why: I didn't change startingPageForScroll

one more thing in the init() function why you didn't use switch instead of "if else if", I know it's not a big deal both work fine, but everyone is saying that switch statement is very powerful in swift, even in Stanford iOS 8 course the professor said the same.
thank you sir

**Comment by fahlout** [comment]
Yeah, there were a few more things that needed to be changed in order to make it work.

Honestly it's just a habit of using if-else statements instead of switch statements, but you're right it would probably be better to use switch statements instead.

**Comment by kalathiyanilesh1** [comment]
When you add parameters in CAPSPageMenu, that time set scrollAnimationDurationOnMenuItemTap(0) and after add it in child view call moveToPage(startpageindex) and than you can update the scrollAnimationDurationOnMenuItemTap value. 

i did this and working perfect. pls check attached SS for code.
![Screenshot 2020-12-21 at 1 06 10 PM](https://user-images.githubusercontent.com/27014642/102751225-4e6abd80-438d-11eb-962f-24719d0d80d0.png)
