### ISSUE TITLE
Minimum iOS Version

### ISSUE THREAD

**Issue by varatep** [uacaps/PageMenu#29]
What's the min iOS version for this? Docs mention iOS 7.1 bugfixes, but podspec declares 8.0.

**Comment by Bautistax** [comment]
I'm pretty sure its 8.0 because everything is written in swift

**Comment by varatep** [comment]
@Bautistax iOS 7 target is compatible with Swift as long as you have a bridging header.

**Comment by ulsc** [comment]
iOS 7 is also compatible with Swift. Actually Swift has nothing to do with iOS versions, it has to do with compiler. And as long as the compiler supports a version, this means compiled code (written in any coding language) supports that version.

**Comment by Grizmol** [comment]
Hi, gyus. Any news about minimum iOS version? I want to use PageMenu in my app but i'm not sure about requirements.

**Comment by fahlout** [comment]
PageMenu was build to support iOS 8. It should work on iOS 7 as well, though, but I can't say for sure for versions below iOS 7 and don't plan on supporting anything below iOS 7 as almost no iOS user out there runs iOS 6 or below anymore

**Comment by Grizmol** [comment]
Ok, thanks for response. Right now I'm testing PageMenu on iOS 7.1 devices and it works fine. Are you planning official support for iOS 7? Like @varatep said, version on cocoapods only supports >8.0 versions.

**Comment by fahlout** [comment]
I might change the cocoa pods spec to iOS 7 and above since it seems to be no problem to use the control in iOS 7

**Comment by jdhealy** [comment]
The dynamic framework CocoaPods builds doesn't work on iOS 7, even though PageMenu as a collection of Swift files does.

Couple References:
<https://github.com/Alamofire/Alamofire/pull/287#discussion_r22523827>
CocoaPods/CocoaPods/issues/2963

**Comment by fahlout** [comment]
Cocoa Pods has to be set to iOS 8 for Swift

**Comment by Narendratha** [comment]
my page menu title with image go to another controller  title image  how to set &
 tableview did select row at indexpath not working

**Comment by satyamub** [comment]
@Narendratha can you please confirm if you are able to use image instead of title ?
