### ISSUE TITLE
Add Reuse Queue

### ISSUE THREAD

**Issue by tljackyi** [uacaps/PageMenu#3]
I think that it would be better to limit numbers of view added in the scrollview,  keeping 3 view in the scrollview once, for better performance.

**Comment by fahlout** [comment]
Thanks for the input! I appreciate any feedback that will help me make this library a better experience for everyone using it as well as for the end user. I will work on getting that worked in as soon as I can.

**Comment by fahlout** [comment]
Resolved in version 1.1.0
