### ISSUE TITLE
how to stay in the same page 

### ISSUE THREAD

**Issue by nthrussell** [uacaps/PageMenu#304]
So far I like this library very much, its been brilliant . Currently I am having an issue is that, in my second page I got a collectionView, from there I got cell on which if I click it navigate into different ViewController. When I navigate back into the second page , it doesn't stay there , it moves to first page of the pagemenu. but I want to stay it on the same page even after navigating back from different page. Hope I could make the situation understand . Please give me some suggestion .

**Comment by nthrussell** [comment]
![simulator screen shot nov 19 2016 4 01 08 pm](https://cloud.githubusercontent.com/assets/10279255/20454665/813684ac-ae71-11e6-90eb-1965da2aa95b.png)
this is my second page 

![simulator screen shot nov 19 2016 4 01 16 pm](https://cloud.githubusercontent.com/assets/10279255/20454667/9238d62e-ae71-11e6-939f-e830a5e29c68.png)
after clicking on the cell it goes to this page

![simulator screen shot nov 19 2016 4 00 55 pm](https://cloud.githubusercontent.com/assets/10279255/20454670/a1e7c350-ae71-11e6-8638-28f08d812829.png)
when I tap back it goes to this first page, does not stay in the second page

**Comment by preetam-idyllic** [comment]
looking for same, any luck?

**Comment by nthrussell** [comment]
not yet mate :(

**Comment by nthrussell** [comment]
please share in you find it as well

**Comment by preetam-idyllic** [comment]
**self.pageMenu?.moveToPage(index)**

worked for me.

But, you should add your pagemenu in viewDidLoad method, so that it wont reinitialise at zero page.

**Comment by MatthewYork** [comment]
Two solutions: 

1. @preetam-idyllic solution to initialize the page menu in viewDidLoad:
2. Add an "isInitialLoad" flag that is toggled once per VC load. Check this in the viewDidAppear. This will allow you to get the precalculated widths/heights of the screen while only loading the page menu once. 

Hope this helps!

-Matt
