### ISSUE TITLE
issue when adding PageMenu in ViewDidLoad method

### ISSUE THREAD

**Issue by preetam-idyllic** [uacaps/PageMenu#307]
Having autolayout issues when configuration done in viewDidLoad method. but its working well when done in viewDidApear.
But I don't want it to add in viewdidApear method. because its re-initialising all after coming back from other screen.

**Comment by biboran** [comment]
The easiest workaround I found is to set open controllerScrollView and menuScrollView and manually set autolayout constraints where you initialize the PageMenu.

**Comment by kurdyukovp** [comment]
@biboran Could you show the code how did you do?

**Comment by biboran** [comment]
So in CAPSPageMenu class you set

`open let menuScrollView = UIScrollView()
    open let controllerScrollView = UIScrollView()`

and in your viewDidLoad you do something like: 
`
containerPageViewController = CAPSPageMenu(
      viewControllers: viewControllers,
      frame: self.view.bounds,
      pageMenuOptions: [
        .menuHeight(64),
        .enableHorizontalBounce(false)
      ])
    
//snp stands for SnapKit
containerPageViewController.menuScrollView.snp.makeConstraints { make in
      make.bottom.equalTo(containerPageViewController.controllerScrollView.subviews.first!.snp.top)
      make.leading.equalTo(containerPageViewController.controllerScrollView)
      make.trailing.equalTo(containerPageViewController.controllerScrollView)
      make.height.equalTo(64)
}

`
As you see it binds the menu to the controllerScrollView (which is where your pages are displayed). Sure this is not an elegant way to do it but it helped me with an issue where my menu would have a 20 points offset from the controllerScrollView.

**Comment by MatthewYork** [comment]
See my answer to #304 . Thanks!
