### ISSUE TITLE
AppStore App - Thank you

### ISSUE THREAD

**Issue by pkgundam** [uacaps/PageMenu#322]
Hi - 

thank you for this awesome library.
This is not really an issue. I did not know how to contact you. I want to thank you for all your work and helping other App developers.

I have used PageMenu in my App - "WhatSport". The app is listed in AppStore as of this week. 

Here is the link - [WhatSport](https://itunes.apple.com/us/app/whatsport-connecting-sports/id1091156941)

Thank you
-Phani

**Comment by fahlout** [comment]
Thanks! Will get that added to the readme!
