### ISSUE TITLE
When is version 2.0.0 going to be released? 

### ISSUE THREAD

**Issue by ndduong97** [uacaps/PageMenu#331]

**Comment by MatthewYork** [comment]
As soon as I can get Nik to add me as an owner to the CocoaPod, which should be today sometime. :-)

**Comment by MatthewYork** [comment]
2.0.0 is released through cocoapods. It is fully Swift 3 compatible! We have also added a configuration struct for cleaner DI. Thanks!

**Comment by ndduong97** [comment]
For some reason when I installed via "pod PageMenu". It's still pulling in 1.2.9. Do you know a fix for this?

**Comment by MatthewYork** [comment]
Do pod update to pull 2.0.0

It is most likely that your local specs repo still only has 1.2.9, which is what pod install uses to source the pod from.

**Comment by wwarder** [comment]
It's still pulling in 1.2.9. Pod update doesn't resolve the issue

**Comment by MatthewYork** [comment]
Is your swift version 3.0? The cocoapod listing shows 2.0.0

https://cocoapods.org/?q=Pagem
