### ISSUE TITLE
Orientation issue

### ISSUE THREAD

**Issue by MaciDE** [uacaps/PageMenu#338]
I discovered an issue where `moveSelectionIndicator(page)` was not called on `scrollViewDidScroll()` due to a problem with the recognition of the current device orientation. In my case` .isPotrait` was false because the device was in `.isFlat` orientation.

I fixed it by changing`currentOrientationIsPortrait = UIDevice.current.orientation.isPortrait` in `viewDidLayoutSubviews()` from `CAPSPageMenu.swift` to `currentOrientationIsPortrait = UIDevice.current.orientation.isPortrait || UIDevice.current.orientation.isFlat`. 

Alternative you can change `currentOrientationIsPortrait = UIDevice.current.orientation.isPortrait` to `currentOrientationIsPortrait = UIApplication.shared.statusBarOrientation.isPortrait`.

**Comment by JackLChen** [comment]
Thank you very much for your reply again. I have already done it.

**Comment by shannonchou** [comment]
I found this issue still exists on master and release 2.0.0. Can you apply it to master and release a new version?

**Comment by MatthewYork** [comment]
I just went to use PageMenu in an app of ours and ran into the same problem. It is now fixed on master, and I will upload a 2.0.1 fix tomorrow. This update biases "unknown" to portrait for the time being.

**Comment by ndduong97** [comment]
Hey, is 2.0.1 uploaded yet?

**Comment by SameerInstacash** [comment]
> I discovered an issue where `moveSelectionIndicator(page)` was not called on `scrollViewDidScroll()` due to a problem with the recognition of the current device orientation. In my case` .isPotrait` was false because the device was in `.isFlat` orientation.
> 
> I fixed it by changing`currentOrientationIsPortrait = UIDevice.current.orientation.isPortrait` in `viewDidLayoutSubviews()` from `CAPSPageMenu.swift` to `currentOrientationIsPortrait = UIApplication.shared.statusBarOrientation.isPortrait`.

Thanks, it's working now in my App.

Thanks again @MaciDE
