### ISSUE TITLE
Dynamically adding VC.

### ISSUE THREAD

**Issue by ashiqsulaiman** [uacaps/PageMenu#343]
I am working on a news application, there is a feature where the user can add categories based on their interest. Every time the user adds a category, it is added to the pagemenu. How do i achieve this?. I tried doing this by creating an xib and creating a vc controller out of it. But this isn't working.` for category in cateogriesArray {
            let controller : UICollectionViewController = UICollectionViewController(nibName: "TopStories", bundle: nil)
            controller.title = category
            vcArray.append(controller)
        }

`
Even if i am able to create the views, how do i display the data for the respective views without a class file.

**Comment by graysonwebster** [comment]
Dynamically adding menu items is going to be fully supported in the next version of PageMenu. We'll have more to say about it soon.

**Comment by mgurnani** [comment]
Is this supported now - "Dynamically adding menu items" ?

**Comment by aadilHaffez** [comment]
@graysonwebster this closed issue means now this library supports dynamic adding vc?
