### ISSUE TITLE
Is it possible to use VIewController instead of nib files? 

### ISSUE THREAD

**Issue by yarodevuci** [uacaps/PageMenu#345]

**Comment by yarodevuci** [comment]
Hi. I don't want to create a nib VC, so I am curious if I can use UIViewControllers for Page menu instead of nib

**Comment by MaciDE** [comment]
Just inistantiate and append them to your controllerArray. 

`let controller1 : YourViewController = self.storyboard?.inistantiateViewController(withIdentifier: "YourVCIdentifier") as! YourViewController"`

**Comment by yarodevuci** [comment]
@MaciDE Thank you!
