### ISSUE TITLE
Swift 1.2 support

### ISSUE THREAD

**Issue by szuniverse** [uacaps/PageMenu#35]
Hi.

Do you plan to upgrade this project to swift 1.2 ?

**Comment by joshjeong** [comment]
+1 yes please support! interfaceOrientation is now deprecated

**Comment by colormyapp** [comment]
Same here, needs update :(

**Comment by fahlout** [comment]
Siwft 1.2 support will come as soon as I get a chance to go through it and fix the issues. it shouldn't be much, so if someone wants to do it and make a pull request that would be greatly appreciated as well!

**Comment by rcgary** [comment]
@fahlout  #36  Support Swift 1.2 
I have not  update for `interfaceOrientation` deprecated. Looks like PageMenu still want to support iOS 7
