### ISSUE TITLE
How to stop moving?

### ISSUE THREAD

**Issue by littlemozart** [uacaps/PageMenu#356]
Hi, it's me again. I also use SlideMenu in my project and I found that when I use the right gesture to open the side menu view, the page will move together. 
![simulator screen shot 2017 4 15 4 41 45](https://cloud.githubusercontent.com/assets/18299148/25062410/3e90befa-21fe-11e7-9f6f-35879fb31c30.png)
I have monitored the status of side menu. So my thought is to make the scroll disable in function willOpen() and enable it again in function didClose().  Is that any way to realize that?

**Comment by littlemozart** [comment]
I have solved. Thanks!

**Comment by lh948** [comment]
I solved my problem in your way, thank you
