### ISSUE TITLE
Despite new update, PageMenu still compiles with warnings: interfaceOrientation is deprecated in iOS 8.

### ISSUE THREAD

**Issue by CHPraxis** [uacaps/PageMenu#37]
As title explains, PageMenu still compiles with warnings after the Swift 1.2 update; can you please resolve the interfaceOrientation issue?

I'd attempt to fix this myself using [UIDevice currentDevice].orientation , but I don't know enough Swift to be useful.  It should be a quick fix.  Thanks!

**Comment by fahlout** [comment]
Yes, warning were not yet worked on, just errors, since it'll still work with warnings. I have not yet figured out what the true equivalent of interfaceOrientation would be since the device orientation property will not give the right orientation at all times

**Comment by benheutmaker** [comment]
Apple's documentation says to replace it with willTransitionToSize. Maybe there could be an enum set up to record the orientation and the state changes when willTransitionToSize is called? I know that this method is better to use with autolayout

**Comment by benheutmaker** [comment]
Just submitted a pull request to fix this issue. Turns out UIDevice.currentDevice().orientation is the correct way of doing this. There's also UIApplication.sharedApplication.statusBarOrientation.Portrait/.Landscape
