### ISSUE TITLE
Update Title ?

### ISSUE THREAD

**Issue by nhjariwala** [uacaps/PageMenu#47]
First of all thanx for the awesome library ... I just want to know that is it possible to update the Title. If user tap or swipe the page then the title should be change. For example in your demo PageMenu is your title then user select music then title should be Music, if user select friend  then title should be Friend and so on ...

Thanks.

**Comment by fahlout** [comment]
You can use the delegate functions didMoveToPage or willMoveToPage and update your title there if I understand you right

**Comment by nhjariwala** [comment]
@fahlout thanks for your prompt response but still I am not able to get it work. Please have look my code

class ViewController: UIViewController, CAPSPageMenuDelegate {

    var pageMenu : CAPSPageMenu?
    
    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        
        // MARK: - UI Setup
        
        self.title = "Sale"
        self.navigationController?.navigationBar.barTintColor = UIColor(red: 0.0/255.0, green: 184.0/255.0, blue: 226.0/255.0, alpha: 1.0)
        self.navigationController?.navigationBar.shadowImage = UIImage()
        self.navigationController?.navigationBar.setBackgroundImage(UIImage(), forBarMetrics: UIBarMetrics.Default)
        self.navigationController?.navigationBar.barStyle = UIBarStyle.Black
        self.navigationController?.navigationBar.tintColor = UIColor.whiteColor()
        self.navigationController?.navigationBar.titleTextAttributes = [NSForegroundColorAttributeName: UIColor.whiteColor()]
        
        pageMenu?.delegate = self

        let imageLeft = UIImage(named: "left_arrow")
        self.navigationItem.leftBarButtonItem = UIBarButtonItem(image: imageLeft, style: UIBarButtonItemStyle.Done, target: self, action: "didTapGoToLeft")
        
        let imageRight = UIImage(named: "right_arrow")
        self.navigationItem.rightBarButtonItem = UIBarButtonItem(image: imageRight, style: UIBarButtonItemStyle.Done, target: self, action: "didTapGoToRight")
        
        // MARK: - Scroll menu setup
        
        // Initialize view controllers to display and place in array
        var controllerArray : [UIViewController] = []
        
        var controllerSale : Sale = Sale(nibName: "SaleLayout", bundle: nil)
        controllerSale.title = "Sale"
        controllerArray.append(controllerSale)
        
        var controllerProfit : Profit = Profit(nibName: "ProfitLayout", bundle: nil)
        controllerProfit.title = "Profit"
        controllerArray.append(controllerProfit)
        
        var controller3 : Customer = Customer(nibName: "CustomerLayout", bundle: nil)
        controller3.title = "No of Customer"
        controllerArray.append(controller3)
        
        var controller4 : AvgSpend = AvgSpend(nibName: "AvgSpendLayout", bundle: nil)
        controller4.title = "Average Spend"
        controllerArray.append(controller4)
        
        var controller5 : Budget = Budget(nibName: "BudgetLayout", bundle: nil)
        controller5.title = "Budget"
        controllerArray.append(controller5)
        
        var parameters: [String: AnyObject] =
        [
            "scrollMenuBackgroundColor": UIColor(red: 241.0/255.0, green: 241.0/255.0, blue: 241.0/255.0, alpha: 1.0),
            "viewBackgroundColor": UIColor.whiteColor(),
            "selectionIndicatorColor": UIColor(red: 115.0/255.0, green: 171.0/255.0, blue: 62.0/255.0, alpha: 1.0),
            "bottomMenuHairlineColor": UIColor.whiteColor(),
            "selectedMenuItemLabelColor": UIColor(red: 115.0/255.0, green: 171.0/255.0, blue: 62.0/255.0, alpha: 1.0),
            "unselectedMenuItemLabelColor": UIColor(red: 255.0/255.0, green: 85.0/255.0, blue: 86.0/255.0, alpha: 1.0),
            "menuItemFont": UIFont(name: "HelveticaNeue", size: 15.0)!,
            "menuHeight": 40.0,
            "menuItemWidth": 130.0,
            "centerMenuItems": true
        ]
        
        // Initialize scroll menu
        pageMenu = CAPSPageMenu(viewControllers: controllerArray, frame: CGRectMake(0.0, 0.0, self.view.frame.width, self.view.frame.height), options: parameters)
        

        self.view.addSubview(pageMenu!.view)
    }
    
    func didTapGoToLeft() {
        var currentIndex = pageMenu!.currentPageIndex

        if currentIndex > 0 {
            pageMenu!.moveToPage(currentIndex - 1)
        }
        setTitleForTab()
    }
    
    func didTapGoToRight() {
        var currentIndex = pageMenu!.currentPageIndex
        
        if currentIndex < pageMenu!.controllerArray.count {
            pageMenu!.moveToPage(currentIndex + 1)
        }
        setTitleForTab()
    }

    func setTitleForTab() {
        var currentIndex = pageMenu!.currentPageIndex
        switch currentIndex {
        case 0:
            self.title = "Sale"
            break
            
        case 1:
            self.title = "Profit"
            break
            
        case 2:
            self.title = "No of Customer"
            break
            
        case 3:
            self.title = "Average Spend"
            break
            
        case 4:
            self.title = "Budget"
            break
            
        default:
            break
        }
    }
}


The above code work fine when user Tap on UIBarButtonItem Left and Right and title successfully changed but I want to change the title in all case like user swipe the page or by selecting specific page. Thanks in advance.

**Comment by nhjariwala** [comment]
I have tried to implement delegate method but not getting success.. Can you please elaborate how can I get it work in my case ? 
Thanks

**Comment by nhjariwala** [comment]
Sorry by mistake clicked on close and comment button so reopen it.

**Comment by fahlout** [comment]
instead of using the didTapGoToLeft and didTapGoToRight functions, use didMoveToPage or  willMoveToPage. From what I can see so far, the reason why your delegate functions don't work is because the delegate for page menu is set before initialization. so move pageMenu?.delegate = self below the following line: pageMenu = CAPSPageMenu(viewControllers: controllerArray, frame: CGRectMake(0.0, 0.0, self.view.frame.width, self.view.frame.height), options: parameters) and then you should be able to use the delegate functions

**Comment by nhjariwala** [comment]
Hi @fahlout  thanks you so much its really simple just need to change the line position and it works like a charm ... thank you so much @fahlout .. many many thanks
