### ISSUE TITLE
CAPSPageMenu PushViewController Not Working

### ISSUE THREAD

**Issue by dathu7728** [uacaps/PageMenu#482]
I'm using CapsPageMenu library (Swift 4)

its very easy to use, but i am getting stuck at pushing view controller from child controller of pageMenu (UITableview did select). using UIButton also its not working. please give me the solution for this in swift 4

**Comment by emirbeytekin** [comment]
self.addChildViewController(pageMenu!)
don't forget this add your root page menu controller
