### ISSUE TITLE
Can't tap tab content, e.g table row..

### ISSUE THREAD

**Issue by thanhtrdang** [uacaps/PageMenu#5]
I see that I can't tap anywhere, except menu.
My workaround solution:
- Bring menuScrollView to front
- Use menuScrollView.addGestureRecognizer(menuItemTapGestureRecognizer) instead of controllerScrollView.addGestureRecognizer(menuItemTapGestureRecognizer)

Please review and apply this patch if this solution is ok for you.

**Comment by fahlout** [comment]
Thanks for your feedback. I worked your solution into the 1.1.1 release.
