### ISSUE TITLE
PageMenu Demos not working properly. 

### ISSUE THREAD

**Issue by lilpennyjr** [uacaps/PageMenu#51]
How did you get it to work? I tried the sample Demos but none of them seem to be working for me. Here is what I get when I run it. 

![screen shot 2015-05-28 at 11 06 24 am 2](https://cloud.githubusercontent.com/assets/11524698/7863370/fb04d45c-0529-11e5-8c15-5373a6b5f850.png)

**Comment by fahlout** [comment]
The demos are currently not converted to the new options that’s why they might not work. Sorry

**Comment by chnhuangyan** [comment]
![2015-06-03 16 29 03](https://cloud.githubusercontent.com/assets/8390780/7955814/b94b278a-0a0d-11e5-9884-c36884fe6cbb.png)
Some code was be commented. Cancel the comments of these code in the above picture then the demo well work properly~  Good Luck!
