### ISSUE TITLE
All didSelectRowAtIndexPath doesn't work in controller

### ISSUE THREAD

**Issue by sezgin** [uacaps/PageMenu#6]
All click actions doesn't work In the CAPS page menu for example collectionView and tableView didSelectRowAtIndexPath action

**Comment by fahlout** [comment]
This was a bug in earlier versions but has been fixed in the latest release (1.1.1). Please download the latest version and check out Demo 4 for an example. Thanks!

**Comment by raeesmadathil** [comment]
I have issue with version 2.0.0, please help me
