### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by wizmeister** [uacaps/PageMenu#7]
First of all, congratulations for the control... it is awesome!

Now... the issue:

If i tap anywhere after the menu items, let's say on demo 1 if i tap right after "favorites" on the black space, the app crashes.

Error screenshot:
![screen shot 2015-01-23 at 5 37 10](https://cloud.githubusercontent.com/assets/2028642/5877219/bf7b4200-a326-11e4-9e7a-876fc6f72491.png)

Full Screenshot:
![screen shot 2015-01-23 at 5 40 08](https://cloud.githubusercontent.com/assets/2028642/5877248/ed8c5d0a-a326-11e4-9196-12cb6ff1d0a7.png)

**Comment by fahlout** [comment]
Thank you for your feedback! I appreciate it!

I have had limited access to a computer in the last couple of days, but I will make sure to look into this issue as soon as I can!

In the meantime please check out the develop branch to take a look at a beta version of using this control in a similar way as a segmented control. There should be a demo project for it as well. It is still work in progress, but should be ready to be released soon.

Thanks!

**Comment by fahlout** [comment]
This issue should be fixed now. Please let me know if you have any more problems with it. Thanks!

**Comment by wizmeister** [comment]
You are awesome, like PageMenu ! :) It is fixed, indeed! Well done!
