### ISSUE TITLE
ios 7 is not supported via Pod

### ISSUE THREAD

**Issue by chlebta** [uacaps/PageMenu#70]
I've installed this library via pod but  I get this warning : 

```
The platform of the target `Pods` (iOS 7.0) may not be compatible with `PageMenu (1.2.8)` which has a minimum requirement of iOS 8.0.
```

but in version history I've noticed it support ios 7.1

**Comment by fahlout** [comment]
That is because swift with cocoa pods only allows iOS 8 and up. To use it with iOS 7 you'll need to download the files from GitHub and put them into your project manually.
