### ISSUE TITLE
Passing data to the view controllers

### ISSUE THREAD

**Issue by lilpennyjr** [uacaps/PageMenu#73]
Is it possible to pass data to the view controllers inside the scroll menu? Every option I've tried has not worked.

**Comment by navidos86** [comment]
here the same i always get a nil returned , though in my parentcontroller where the pagemenu is added there everything goes fine. 

is there someone who can help me out with this?

**Comment by anastasia-kovaleva** [comment]
Did it via NSURLDefaults.

**Comment by Jake-Piatkowski** [comment]
I just had the same problem it seems: I tried to keep references to the ViewControllers which I added into the PageMenu but their ivars were always set to nil when I tried to access them.

What worked for me was accessing the ViewControllers through the PageMenu's controllerArray each time I wanted to perform anything on them.

**Comment by KwesiCobbina** [comment]
> I just had the same problem it seems: I tried to keep references to the ViewControllers which I added into the PageMenu but their ivars were always set to nil when I tried to access them.
> 
> What worked for me was accessing the ViewControllers through the PageMenu's controllerArray each time I wanted to perform anything on them.

How? Could you post an example.
