### ISSUE TITLE
Remove PageMenu

### ISSUE THREAD

**Issue by grizzly** [uacaps/PageMenu#76]
How to remove the pagemenu completly? I would like to load a different menu from server, which should replace the old pagemenu with a new pagemenu (and new subview of course).

**Comment by grizzly** [comment]
ended up with: view.subviews.map({ $0.removeFromSuperview() })

seems to work

**Comment by TaoufikBouabid** [comment]
view.subviews.map({ $0.removeFromSuperview() }) will remove all the subviews of your viewcontroller instead use: pageMenu.view.removeFromSuperview()
