### ISSUE TITLE
Presenting view controllers on detached view controllers is discouraged

### ISSUE THREAD

**Issue by griffonixjp** [uacaps/PageMenu#77]
Thanks for the great library.

I have pageMenu and 3 child viewControllers.
One of them has collectionView and when a cell is tapped, presentViewController method is called in didSelectItemAtIndexPath.
Then, the following warning displays in debug window.

> Presenting view controllers on detached view controllers is discouraged

The modal viewcontroller is displayed properly but when dismissViewControllerAnimated is called, source view layout collapses and the view goes under navigationbar.
How can I prevent from the warning?
I tried the following code but when dismissViewControllerAnimated is called, EXC_BAD_ACCESS error occurs.

    self.view.window!.rootViewController?.presentViewController(vc, animated: true, completion: nil)

Swift 1.2
XCode 5.3.1

**Comment by paulsfds** [comment]
When you add the PageMenu VC to your view hierarchy, make sure you add it as a child view controller.
```
// Initialize page menu with controller array, frame, and optional parameters
var pageMenu = CAPSPageMenu(viewControllers: controllerArray, frame: CGRectMake(0.0, 0.0, self.view.frame.width, self.view.frame.height), pageMenuOptions: parameters)
   
[self addChildViewController: self.pageMenu];       
[self.view addSubview: self.pageMenu.view];
[self.pageMenu didMoveToParentViewController: self];        
```

**Comment by griffonixjp** [comment]
Cool! It works like a charm!
Thank you, paulsfds

**Comment by patelmayank** [comment]
works like charm !! 
Thank you @paulsfds
