### ISSUE TITLE
Possible bug? or maybe feature request...

### ISSUE THREAD

**Issue by wizmeister** [uacaps/PageMenu#8]
Hi! It's me again, and once again congrats for PageMenu!

Lets say I have a tableviewcontroller as one of the pages, and I have a pop segue on the cell.

Then, on the view controller that has popped I have a dismiss button: self.dismissViewControllerAnimated(true, completion: nil)

When I dismiss the view controller I see the tableview and after a second PageMenu gets me back to the first view controller of the array.

Maybe some of the settings must be moved to ViewDidLoad instead of viewdidAppear?

**Comment by wizmeister** [comment]
Moving everything to View Did Load and leaving just self.view.addSubview(pageMenu!.view) on the viewdidappear seems to solve the issue ;)

**Comment by fahlout** [comment]
I'm glad you found a way to solve your issue. I will leave the issue open until I get around to looking at the issue and seeing if your fix can be a permanent fix. Thanks!

**Comment by wizmeister** [comment]
I am coming back with an issue... If i put everything rather than the add.subview on view did load then I do not get correct sizes on the view controller content, for example if I have a tableview then the last cells are after the view controller bottom bounds and even if i "scroll" down then it just goes up again and it is impossible to view or select the tableview cell...

**Comment by fahlout** [comment]
I have been working on making the setup easier and being able to put everything in view did load. Currently it's just in the develop branch as I am working on a few more improvements. So until the next release please check out the develop branch to see what I am working on for the next release.

Thanks!

**Comment by wizmeister** [comment]
That's great! I have more feedback (on the main release branch version):

Let's say I put everything except addsubview on the viewdidload, if I have on the navigation bar (which is on the main view controller, ok?) a bar button with a pop segue, on whichever page I am except the first one, when I tap the button then the app crashes.

**Comment by fahlout** [comment]
Sorry for the late response. I would need more specifics to track down the problem. I am in the process of getting ready to release version 1.2.1. I'm not sure if it'll fix your problem but if it doesn't please clarify a little more what you are trying to do.

Thanks!

**Comment by wizmeister** [comment]
Hi! Please let me check this tomorrow morning (it's almost 22:00 here) when I will have access to my Mac. I need to double check if I can reproduce the problem.

**Comment by wizmeister** [comment]
Hello,

Strangely, I cannot reproduce the problem...

**Comment by fahlout** [comment]
I'm glad the problem seems to be gone. I will close the issue for now, but please let me know if you experience any more issues
