### ISSUE TITLE
Feature request - event callbacks

### ISSUE THREAD

**Issue by jyounus** [uacaps/PageMenu#9]
Hi there,

I have a suggestion for this awesome little git project. Event callbacks/delegates/closure calls (whatever you want to call it) for when the app displays a page. 

So lets say we have page A, page B and page C. If A is active and user taps on page C, after the animation has finished, fire this 'callback' function to do any necessary updates (i.e. updating the colour of the navigation bar based on the active page in a different view controller file). Same would apply if the user simply scrolled left or right, fire/call the appropriate thing and make sure to pass back the reference of the active page that the user scrolled to.

Would be really useful, at least for me. :)

**Comment by fahlout** [comment]
I agree, it would be a very helpful feature. I will start working on it tomorrow. Currently I am working on some small setup improvements, so once that is done I will start on this. Should be available within the next couple days.

Thanks for your feedback and I'm glad you're enjoying the library :)

**Comment by jyounus** [comment]
Awesome, looking forward to it! :D

**Comment by fahlout** [comment]
I added this feature, but it currently is only available in the develop branch as I am working on a couple more things for the next release. I just thought I'd let you know it's there so you can start looking at it and using it. Of course anything in the develop branch is in beta so it might not all work correctly at the moment. A new release should be out in a few days though

**Comment by jyounus** [comment]
Perfect, will grab the latest changes and play around with it when I get some time. Thanks!

**Comment by attheodo** [comment]
@fahlout If I may recommend some enhancements too:
- Expose menuItemSeparator's backgroundColor as a property
- Find a neat way to make `interactivePopGestureRecognizer` work when PageMenu displays the leftmost UIViewController. Currently, the UIScrollView intercepts the gesture and just bounces horizontally.

Thanks and props for the cool lib. Saved me lots of time buddy.

**Comment by fahlout** [comment]
I will make sure to make that a property. Can you clarify what you're trying to do in the second bullet point  a little more please?
Your third issue should fix itself with a new release in the coming days.

Are you trying to put view controllers with navigation controllers in the page menu? Currently the only thing that's supported even though more things than are supported technically work it is not made to be able to push anything within the view controllers in page menu. Anything being pushed should be pushed from the parent view controller that you set up page menu in. This is just how it is right now

**Comment by attheodo** [comment]
Hey @fahlout,

thanks for your prompt response buddy. So.. regarding the second bullet point. Currently, in my hierarchy all the view controllers in the UINavigationController stack have custom UINavigationBars. These are set as IBOutlets and customised by each view. Under these circumstances, I want to be able to support the swipe from left edge-to-right to go back one view controller. This has the same effect as tapping the back button in the navigation bar. Unfortunately, if there's a PageMenu in the view, it's scroll view intercepts this swipe gesture and just bounces the scrollview instead of poping the current view controller and going back. Is that more clear?

Also, no.. I am not pushing UINavigation controllers in the PageMenu although the PageMenu is in a view controller that is encapsulated in a UINavigationController. 

Please, do let me know if you need any more clarifications.

**Comment by fahlout** [comment]
Interesting. I think i understand what you're trying to do now. I would have to research this a little more to see what's possible in this situation as this is something I did not think of so thanks for bringing that up. I wonder if setting the scroll view in page menu to not bounce will make any difference.

**Comment by fahlout** [comment]
I'm going to commit something to demo 5 in the develop branch that I will get rid of again after I get a response from you. Please let me know if that is similar to your setup navigation wise

**Comment by attheodo** [comment]
@fahlout sorry I was AFK and didn't catch up soon enough. I checked you commit in develop branch. No, my setup is not like that. PageMenu controllers are all UIViewControllers. But PageMenu belongs to a UIViewController that is part of a UINavigationController stack. Why are you investigating this setup? Is it because of the "blinking" issue or the swipe thing?

**Comment by fahlout** [comment]
The blinking issue should be resolved once I release the next version. I'm wondering because of the swipe thing. Can you give me a screenshot/video or some code just so I know for sure what your setup is in order to either look for a fix or help you with a setup issue?

**Comment by attheodo** [comment]
@fahlout thanks for your interest. Check out what I am talking about here. Let me know if you need further clarifications. https://www.dropbox.com/s/f4kiq6kynib4oz4/movie.mov?dl=0

**Comment by fahlout** [comment]
Before I try to speculate more about reasons why it's not working I would like to know if you have tried it on an actual iphone. I tried setting up something like this and it worked with no problem on my phone. Sometimes the simulator doesn't work correctly for some of the features. Would be nice if it's just a simulator problem haha

**Comment by attheodo** [comment]
I did test it on an iPhone6. Unfortunately it didn't work there too. If you think there's something you can tweak on your end, please go ahead. If you think it's something non-trivial to PageMenu I'll try to find another way on my own. Thanks anyway man.

**Comment by attheodo** [comment]
By the way, please do expose a property for disallowing the horizontal bouncing as well. Some users might find it useful.

**Comment by fahlout** [comment]
That is really odd that it won't work for you. I should be making another release today, which will require a slightly different setup for page menu. Once if have that out please let me know if you're still having the same issue. I you do I'll try to figure something out. 

I do like how your app looks though! Please let me know when you release it so I can add you to the section on github for apps that use this controller.

I will add another property for horizontal bouncing as well. If you think of any other properties that might be useful please let me know.

Thanks!

**Comment by attheodo** [comment]
@fahlout thanks for your kinds words. I will sure let you know when it's released.

Another thing that literally just occurred to me for this project is this:
- In some circumstances I want the page menu to have only one view controller so a "segmentation menu" is useless and I'd like to hide it. I tried setting the `menuHeight` property to `0` but I can still see a very thin gray line at the top. I am assuming this is a border line of the menu of some sorts. It'd be good if there was a boolean way to show/hide the menu or at least expose some other styling properties of it so I can make the line disappear without directly messing with your code :)

**Comment by fahlout** [comment]
I will consider adding a property for just hiding the menu on top. Currently setting the height to 0 and setting the addBottomMenuHairline to false will hide it.

Thanks for your suggestions! I appreciate it!

**Comment by attheodo** [comment]
I thank you for your support man. Keep it up!

**Comment by qky1412** [comment]
@fahlout @attheodo  thanks for ur work, but I wanna know if the "swipe back gesture(pop current viewcontroller) is enabled when in first page" problem is solved, it seems that it still doesn't work for me right now even if i disable the horizontal bounce to the pageMenu.
